# TODO: update this from inside the build to use branch current version
version: '{build}'

#cache:
#- 'C:\Python38\'
#- 'C:\Python38-x64'

environment:
  libyaml_repo_url: https://github.com/yaml/libyaml.git
  libyaml_refspec: 0.2.2
  PYYAML_TEST_GROUP: all


  matrix:
    - PYTHON_VER: Python27
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python27-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python35
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python35-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python36
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python36-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python37
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python37-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python38
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python38-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python39
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON_VER: Python39-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- ps: packaging\build\appveyor.ps1

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
